blueprint:
  name: Boks Notifications
  description: >
    All-in-one automation for your Boks Parcel Box.
    Sends notifications to your mobile device for:
    - Parcel Deliveries (when a Todo list code is used)
    - Door Openings
    - Invalid Code Attempts
    - Low Battery
  domain: automation
  input:
    log_entity:
      name: Boks Log Event Entity
      description: Select the event entity (e.g., event.my_boks_logs)
      selector:
        entity:
          domain: event
          integration: boks
    battery_entity:
      name: Boks Battery Sensor
      description: Select the battery sensor (e.g., sensor.my_boks_battery)
      selector:
        entity:
          domain: sensor
          device_class: battery
          integration: boks
    notify_device:
      name: Mobile Device to Notify
      description: The device that will receive the notifications.
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: event
    event_type: boks_parcel_completed
    id: parcel_delivered
  - platform: state
    entity_id: !input log_entity
    attribute: event_type
    to: "door_opened"
    id: door_opened
  - platform: state
    entity_id: !input log_entity
    attribute: event_type
    to:
      - "code_ble_invalid"
      - "code_key_invalid"
    id: invalid_code
  - platform: numeric_state
    entity_id: !input battery_entity
    below: 15
    id: low_battery

action:
  - choose:
      - conditions:
          - condition: trigger
            id: parcel_delivered
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "📦 Parcel Delivered"
            message: "Parcel '{{ trigger.event.data.description }}' was delivered using code {{ trigger.event.data.code }}."

      - conditions:
          - condition: trigger
            id: door_opened
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "📬 Boks Opened"
            message: "Your Boks has been opened."

      - conditions:
          - condition: trigger
            id: invalid_code
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "🚨 Boks Security Alert"
            message: "An invalid code attempt was detected on your Boks!"

      - conditions:
          - condition: trigger
            id: low_battery
        sequence:
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "🪫 Boks Battery Low"
            message: "Your Boks battery is critical ({{ trigger.to_state.state }}%). Please replace it."
